import type { PrismaClient } from "@/generated/prisma/client";
import type { ReferralPostModel } from "@/generated/prisma/models/ReferralPost";
import type { FulfillmentCheckModel } from "@/generated/prisma/models/FulfillmentCheck";
import { resend } from "@/lib/email/resend";
import {
  FulfillmentCheckEmail,
  fulfillmentCheckSubject,
} from "@/lib/email/templates/fulfillment-check";

const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000";
const FROM_EMAIL = process.env.RESEND_FROM_EMAIL ?? "noreply@example.com";

/**
 * Creates a FulfillmentCheck record and sends a fulfillment check email
 * to the referral author asking whether the referral was fulfilled.
 *
 * @returns The created FulfillmentCheck record
 */
export async function sendFulfillmentCheck(
  referralPost: ReferralPostModel,
  prisma: PrismaClient,
): Promise<FulfillmentCheckModel> {
  // Fetch the author's profile and user email
  const author = await prisma.therapistProfile.findUniqueOrThrow({
    where: { id: referralPost.authorId },
    include: { user: { select: { email: true, name: true } } },
  });

  // Create the fulfillment check record (token is auto-generated by Prisma default)
  const fulfillmentCheck = await prisma.fulfillmentCheck.create({
    data: {
      referralPostId: referralPost.id,
    },
  });

  const fulfillYesUrl = `${APP_URL}/referrals/fulfill/${fulfillmentCheck.token}?fulfilled=true`;
  const fulfillNoUrl = `${APP_URL}/referrals/fulfill/${fulfillmentCheck.token}?fulfilled=false`;

  const referrerName = author.user.name ?? `${author.firstName} ${author.lastName}`;

  const { error } = await resend.emails.send({
    from: FROM_EMAIL,
    to: author.user.email,
    subject: fulfillmentCheckSubject(),
    react: FulfillmentCheckEmail({
      baseUrl: APP_URL,
      referrerName,
      presentingIssue: referralPost.presentingIssue,
      city: referralPost.city,
      province: referralPost.province ?? "Unknown",
      fulfillYesUrl,
      fulfillNoUrl,
    }),
  });

  if (error) {
    console.error(
      `Failed to send fulfillment check for referral ${referralPost.id}:`,
      error.message,
    );
  }

  return fulfillmentCheck;
}
