import type { PrismaClient } from "@/generated/prisma/client";
import type { ReferralPostModel } from "@/generated/prisma/models/ReferralPost";
import type { FulfillmentCheckModel } from "@/generated/prisma/models/FulfillmentCheck";
import { sendEmailWithRetry } from "@/lib/email/send-with-retry";
import {
  FulfillmentCheckEmail,
  fulfillmentCheckSubject,
} from "@/lib/email/templates/fulfillment-check";
import { getAppUrl, getResendFromEmail, getSupportEmail } from "@/lib/env";

const APP_URL = getAppUrl();
const FROM_EMAIL = getResendFromEmail();

/**
 * Creates a FulfillmentCheck record and sends a fulfillment check email
 * to the referral author asking whether the referral was fulfilled.
 *
 * @returns The created FulfillmentCheck record
 */
export async function sendFulfillmentCheck(
  referralPost: ReferralPostModel,
  prisma: PrismaClient,
): Promise<FulfillmentCheckModel> {
  // Fetch the author's profile and user email
  const author = await prisma.therapistProfile.findUniqueOrThrow({
    where: { id: referralPost.authorId },
    include: { user: { select: { email: true, name: true } } },
  });

  // Create the fulfillment check record (token is auto-generated by Prisma default)
  const fulfillmentCheck = await prisma.fulfillmentCheck.create({
    data: {
      referralPostId: referralPost.id,
    },
  });

  // Single landing URL — recipient confirms via form POST on the page,
  // not a GET, so email prefetchers / link scanners cannot record a
  // response by visiting the link.
  const fulfillUrl = `${APP_URL}/referrals/fulfill/${fulfillmentCheck.token}`;

  const referrerName = author.user.name ?? `${author.firstName} ${author.lastName}`;

  const { error } = await sendEmailWithRetry({
    from: FROM_EMAIL,
    replyTo: getSupportEmail(),
    to: author.user.email,
    subject: fulfillmentCheckSubject(),
    react: FulfillmentCheckEmail({
      baseUrl: APP_URL,
      referrerName,
      presentingIssue: referralPost.presentingIssue,
      city: referralPost.city,
      province: referralPost.province ?? "Unknown",
      fulfillUrl,
    }),
  });

  if (error) {
    console.error(
      `Failed to send fulfillment check for referral ${referralPost.id}:`,
      error.message,
    );
  }

  return fulfillmentCheck;
}
